export default {
  keys:
  {
    row1: [
      {
        en: '`',
        altEn: '~',
        ru: 'ё',
        altRu: 'Ё',
        code: 'Backquote',
        classList: ['key', 'key_fixed', 'subkey'],
      },
      {
        en: '1',
        altEn: '!',
        ru: '1',
        altRu: '!',
        code: 'Digit1',
        classList: ['key', 'subkey'],
      },
      {
        en: '2',
        altEn: '@',
        ru: '2',
        altRu: '"',
        code: 'Digit2',
        classList: ['key', 'subkey'],
      },
      {
        en: '3',
        altEn: '#',
        ru: '3',
        altRu: '№',
        code: 'Digit3',
        classList: ['key', 'subkey'],
      },
      {
        en: '4',
        altEn: '$',
        ru: '4',
        altRu: ';',
        code: 'Digit4',
        classList: ['key', 'subkey'],
      },
      {
        en: '5',
        altEn: '%',
        ru: '5',
        altRu: '%',
        code: 'Digit5',
        classList: ['key', 'subkey'],
      },
      {
        en: '6',
        altEn: '^',
        ru: '6',
        altRu: ':',
        code: 'Digit6',
        classList: ['key', 'subkey'],
      },
      {
        en: '7',
        altEn: '&',
        ru: '7',
        altRu: '?',
        code: 'Digit7',
        classList: ['key', 'subkey'],
      },
      {
        en: '8',
        altEn: '*',
        ru: '8',
        altRu: '*',
        code: 'Digit8',
        classList: ['key', 'subkey'],
      },
      {
        en: '9',
        altEn: '(',
        ru: '9',
        altRu: '(',
        code: 'Digit9',
        classList: ['key', 'subkey'],
      },
      {
        en: '0',
        altEn: ')',
        ru: '0',
        altRu: ')',
        code: 'Digit0',
        classList: ['key', 'subkey'],
      },
      {
        en: '-',
        altEn: '_',
        ru: '-',
        altRu: '_',
        code: 'Minus',
        classList: ['key', 'subkey'],
      },
      {
        en: '=',
        altEn: '+',
        ru: '=',
        altRu: '+',
        code: 'Equal',
        classList: ['key', 'subkey'],
      },
      {
        en: 'Backspace',
        altEn: 'Backspace',
        ru: 'Backspace',
        altRu: 'Backspace',
        code: 'Backspace',
        classList: ['key', 'key_special', 'key_fn', 'key_backspace'],
      }],
    row2: [
      {
        en: 'Tab',
        altEn: 'Tab',
        ru: 'Tab',
        altRu: 'Tab',
        code: 'Tab',
        classList: ['key', 'key_special', 'key_tab'],
      },
      {
        en: 'q',
        altEn: 'Q',
        ru: 'й',
        altRu: 'Й',
        code: 'KeyQ',
        classList: ['key'],
      },
      {
        en: 'w',
        altEn: 'W',
        ru: 'ц',
        altRu: 'Ц',
        code: 'KeyW',
        classList: ['key'],
      },
      {
        en: 'e',
        altEn: 'E',
        ru: 'у',
        altRu: 'У',
        code: 'KeyE',
        classList: ['key'],
      },
      {
        en: 'r',
        altEn: 'R',
        ru: 'к',
        altRu: 'К',
        code: 'KeyR',
        classList: ['key'],
      },
      {
        en: 't',
        altEn: 'T',
        ru: 'е',
        altRu: 'Е',
        code: 'KeyT',
        classList: ['key'],
      },
      {
        en: 'y',
        altEn: 'Y',
        ru: 'н',
        altRu: 'Н',
        code: 'KeyY',
        classList: ['key'],
      },
      {
        en: 'u',
        altEn: 'U',
        ru: 'г',
        altRu: 'Г',
        code: 'KeyU',
        classList: ['key'],
      },
      {
        en: 'i',
        altEn: 'I',
        ru: 'ш',
        altRu: 'Ш',
        code: 'KeyI',
        classList: ['key'],
      },
      {
        en: 'o',
        altEn: 'O',
        ru: 'щ',
        altRu: 'Щ',
        code: 'KeyO',
        classList: ['key'],
      },
      {
        en: 'p',
        altEn: 'P',
        ru: 'з',
        altRu: 'З',
        code: 'KeyP',
        classList: ['key'],
      },
      {
        en: '[',
        altEn: '{',
        ru: 'х',
        altRu: 'Х',
        code: 'BracketLeft',
        classList: ['key', 'subkey'],
      },
      {
        en: ']',
        altEn: '}',
        ru: 'ъ',
        altRu: 'Ъ',
        code: 'BracketRight',
        classList: ['key', 'subkey'],
      },
      {
        en: '\\',
        altEn: '|',
        ru: '\\',
        altRu: '/',
        code: 'Backslash',
        classList: ['key', 'subkey'],
      },
      {
        en: 'Del',
        altEn: 'Del',
        ru: 'Del',
        altRu: 'Del',
        code: 'Delete',
        classList: ['key', 'key_special', 'key_fn', 'key_del'],
      }],
    row3: [
      {
        en: 'Caps Lock',
        altEn: 'Caps Lock',
        ru: 'Caps Lock',
        altRu: 'Caps Lock',
        code: 'CapsLock',
        classList: ['key', 'key_special', 'key_fn', 'key_caps'],
      },
      {
        en: 'a',
        altEn: 'A',
        ru: 'ф',
        altRu: 'Ф',
        code: 'KeyA',
        classList: ['key'],
      },
      {
        en: 's',
        altEn: 'S',
        ru: 'ы',
        altRu: 'Ы',
        code: 'KeyS',
        classList: ['key'],
      },
      {
        en: 'd',
        altEn: 'D',
        ru: 'в',
        altRu: 'В',
        code: 'KeyD',
        classList: ['key'],
      },
      {
        en: 'f',
        altEn: 'F',
        ru: 'а',
        altRu: 'А',
        code: 'KeyF',
        classList: ['key'],
      },
      {
        en: 'g',
        altEn: 'G',
        ru: 'п',
        altRu: 'П',
        code: 'KeyG',
        classList: ['key'],
      },
      {
        en: 'h',
        altEn: 'H',
        ru: 'р',
        altRu: 'Р',
        code: 'KeyH',
        classList: ['key'],
      },
      {
        en: 'j',
        altEn: 'J',
        ru: 'о',
        altRu: 'О',
        code: 'KeyJ',
        classList: ['key'],
      },
      {
        en: 'k',
        altEn: 'K',
        ru: 'л',
        altRu: 'Л',
        code: 'KeyK',
        classList: ['key'],
      },
      {
        en: 'l',
        altEn: 'L',
        ru: 'д',
        altRu: 'Д',
        code: 'KeyL',
        classList: ['key'],
      },
      {
        en: ';',
        altEn: ':',
        ru: 'ж',
        altRu: 'Ж',
        code: 'Semicolon',
        classList: ['key'],
      },
      {
        en: "'",
        altEn: '"',
        ru: 'э',
        altRu: 'Э',
        code: 'Quote',
        classList: ['key'],
      },
      {
        en: 'Enter',
        altEn: 'Enter',
        ru: 'Enter',
        altRu: 'Enter',
        code: 'Enter',
        classList: ['key', 'key_special', 'key_enter'],
      }],
    row4: [
      {
        en: 'Shift',
        altEn: 'Shift',
        ru: 'Shift',
        altRu: 'Shift',
        code: 'ShiftLeft',
        classList: ['key', 'key_special', 'key_fn', 'key_shift-left'],
      },
      {
        en: 'z',
        altEn: 'Z',
        ru: 'я',
        altRu: 'Я',
        code: 'KeyZ',
        classList: ['key'],
      },
      {
        en: 'x',
        altEn: 'X',
        ru: 'ч',
        altRu: 'Ч',
        code: 'KeyX',
        classList: ['key'],
      },
      {
        en: 'c',
        altEn: 'C',
        ru: 'с',
        altRu: 'С',
        code: 'KeyC',
        classList: ['key'],
      },
      {
        en: 'v',
        altEn: 'V',
        ru: 'м',
        altRu: 'М',
        code: 'KeyV',
        classList: ['key'],
      },
      {
        en: 'b',
        altEn: 'B',
        ru: 'и',
        altRu: 'И',
        code: 'KeyB',
        classList: ['key'],
      },
      {
        en: 'n',
        altEn: 'N',
        ru: 'т',
        altRu: 'Т',
        code: 'KeyN',
        classList: ['key'],
      },
      {
        en: 'm',
        altEn: 'M',
        ru: 'ь',
        altRu: 'Ь',
        code: 'KeyM',
        classList: ['key'],
      },
      {
        en: ',',
        altEn: '<',
        ru: 'б',
        altRu: 'Б',
        code: 'Comma',
        classList: ['key'],
      },
      {
        en: '.',
        altEn: '>',
        ru: 'ю',
        altRu: 'Ю',
        code: 'Period',
        classList: ['key'],
      },
      {
        en: '/',
        altEn: '?',
        ru: '.',
        altRu: ',',
        code: 'Slash',
        classList: ['key'],
      },
      {
        en: '↑',
        altEn: '↑',
        ru: '↑',
        altRu: '↑',
        code: 'ArrowUp',
        classList: ['key', 'key_special', 'key_fixed', 'key_arrow_up'],
      },
      {
        en: 'Shift',
        altEn: 'Shift',
        ru: 'Shift',
        altRu: 'Shift',
        code: 'ShiftRight',
        classList: ['key', 'key_special', 'key_fn', 'key_fixed', 'key_shift-right'],
      }],
    row5: [
      {
        en: 'Ctrl',
        altEn: 'Ctrl',
        ru: 'Ctrl',
        altRu: 'Ctrl',
        code: 'ControlLeft',
        classList: ['key', 'key_special', 'key_fn', 'key_ctrl-left'],
      },
      {
        en: 'Win',
        altEn: 'Win',
        ru: 'Win',
        altRu: 'Win',
        code: 'MetaLeft',
        classList: ['key', 'key_special', 'key_fn', 'key_win'],
      },
      {
        en: 'Alt',
        altEn: 'Alt',
        ru: 'Alt',
        altRu: 'Alt',
        code: 'AltLeft',
        classList: ['key', 'key_special', 'key_fn', 'key_alt-left'],
      },
      {
        en: ' ',
        altEn: ' ',
        ru: ' ',
        altRu: ' ',
        code: 'Space',
        classList: ['key', 'key_space'],
      },
      {
        en: 'Alt',
        altEn: 'Alt',
        ru: 'Alt',
        altRu: 'Alt',
        code: 'AltRight',
        classList: ['key', 'key_special', 'key_fn', 'key_alt-right'],
      },
      {
        en: 'Ctrl',
        altEn: 'Ctrl',
        ru: 'Ctrl',
        altRu: 'Ctrl',
        code: 'ControlRight',
        classList: ['key', 'key_special', 'key_fn', 'key_ctrl-right'],
      },
      {
        en: '←',
        altEn: '←',
        ru: '←',
        altRu: '←',
        code: 'ArrowLeft',
        classList: ['key', 'key_special', 'key_fixed', 'key_arrow_left'],
      },
      {
        en: '↓',
        altEn: '↓',
        ru: '↓',
        altRu: '↓',
        code: 'ArrowDown',
        classList: ['key', 'key_special', 'key_fixed', 'key_arrow_down'],
      },
      {
        en: '→',
        altEn: '→',
        ru: '→',
        altRu: '→',
        code: 'ArrowRight',
        classList: ['key', 'key_special', 'key_fixed', 'key_arrow_right'],
      },
    ],
  },
};
